(deftheme cyberpunk
  "Created 2019-08-31.")

(custom-theme-set-variables
 'cyberpunk
 '(ansi-color-names-vector ["#000000" "#8b0000" "#00ff00" "#ffa500" "#7b68ee" "#dc8cc3" "#93e0e3" "#dcdccc"]))

(custom-theme-set-faces
 'cyberpunk
 '(button ((t (:underline t))))
 '(link ((((class color) (min-colors 89)) (:foreground "#ffff00" :underline t :weight bold))))
 '(link-visited ((((class color) (min-colors 89)) (:foreground "#d0bf8f" :underline t :weight normal))))
 '(bold ((((class color) (min-colors 89)) (:bold t))))
 '(cursor ((((class color) (min-colors 89)) (:background "#dcdccc"))))
 '(fringe ((((class color) (min-colors 89)) (:foreground "#dcdccc" :background "#2b2b2b"))))
 '(header-line ((((class color) (min-colors 89)) (:foreground "#ffff00" :background "#2b2b2b" :box (:line-width -1 :style released-button)))))
 '(highlight ((((class color) (min-colors 89)) (:background "#333333"))))
 '(compilation-info ((((class color) (min-colors 89)) (:foreground "#bfebbf" :underline t))))
 '(compilation-line-number ((((class color) (min-colors 89)) (:foreground "#ffff00"))))
 '(match ((((class color) (min-colors 89)) (:background "#000000" :foreground "#ff1493"))))
 '(isearch ((((class color) (min-colors 89)) (:foreground "#000000" :background "#ff1493"))))
 '(isearch-fail ((((class color) (min-colors 89)) (:background "#8b0000"))))
 '(lazy-highlight ((((class color) (min-colors 89)) (:foreground "#000000" :background "#ffff00"))))
 '(query-replace ((((class color) (min-colors 89)) (:background "#333333"))))
 '(menu ((((class color) (min-colors 89)) (:foreground "#dcdccc" :background "#000000"))))
 '(minibuffer-prompt ((((class color) (min-colors 89)) (:foreground "#61CE3C" :background "#000000"))))
 '(mode-line ((((class color) (min-colors 89)) (:foreground "#4c83ff" :background "#333333" :box (:line-width -1 :color "#4c83ff")))))
 '(mode-line-inactive ((((class color) (min-colors 89)) (:foreground "#4D4D4D" :background "#1A1A1A" :box (:line-width -1 :color "#4c83ff")))))
 '(region ((((class color) (min-colors 89)) (:background "#7F073F"))))
 '(secondary-selection ((((class color) (min-colors 89)) (:background "#5f5f5f"))))
 '(trailing-whitespace ((((class color) (min-colors 89)) (:background "#ff0000"))))
 '(vertical-border ((((class color) (min-colors 89)) (:foreground "#333333" :background "#000000"))))
 '(font-lock-builtin-face ((((class color) (min-colors 89)) (:foreground "#4c83ff"))))
 '(font-lock-comment-face ((((class color) (min-colors 89)) (:foreground "#8B8989" :italic t))))
 '(font-lock-constant-face ((((class color) (min-colors 89)) (:foreground "#96CBFE"))))
 '(font-lock-doc-face ((((class color) (min-colors 89)) (:foreground "#FBDE2D"))))
 '(font-lock-function-name-face ((((class color) (min-colors 89)) (:foreground "#ff1493"))))
 '(font-lock-keyword-face ((((class color) (min-colors 89)) (:foreground "#4c83ff"))))
 '(font-lock-preprocessor-face ((((class color) (min-colors 89)) (:foreground "#919191"))))
 '(font-lock-string-face ((((class color) (min-colors 89)) (:foreground "#61CE3C"))))
 '(font-lock-type-face ((((class color) (min-colors 89)) (:foreground "#afd8af"))))
 '(font-lock-variable-name-face ((((class color) (min-colors 89)) (:foreground "#ff69b4"))))
 '(font-lock-warning-face ((((class color) (min-colors 89)) (:foreground "#ff69b4"))))
 '(font-lock-regexp-grouping-backslash ((((class color) (min-colors 89)) (:foreground "#E9C062"))))
 '(font-lock-regexp-grouping-construct ((((class color) (min-colors 89)) (:foreground "#ff0000"))))
 '(c-annotation-face ((((class color) (min-colors 89)) (:inherit font-lock-constant-face))))
 '(ac-completion-face ((((class color) (min-colors 89)) (:background "#8B8989" :underline t))))
 '(ac-candidate-face ((((class color) (min-colors 89)) (:background "#999999" :foreground "#000000"))))
 '(ac-selection-face ((((class color) (min-colors 89)) (:background "#ff1493" :foreground "#000000"))))
 '(popup-tip-face ((((class color) (min-colors 89)) (:background "#333333" :foreground "#ffffff"))))
 '(popup-scroll-bar-foreground-face ((((class color) (min-colors 89)) (:background "#0A0A0A"))))
 '(popup-isearch-match ((((class color) (min-colors 89)) (:background "#000000" :foreground "#ff1493"))))
 '(diff-added ((((class color) (min-colors 89)) (:foreground "#00ff00"))))
 '(diff-changed ((((class color) (min-colors 89)) (:foreground "#ffff00"))))
 '(diff-removed ((((class color) (min-colors 89)) (:foreground "#ff0000"))))
 '(diff-header ((((class color) (min-colors 89)) (:background "#5f5f5f"))))
 '(diff-file-header ((((class color) (min-colors 89)) (:background "#5f5f5f" :foreground "#dcdccc" :bold t))))
 '(flymake-error ((((class color) (min-colors 89)) (:foreground "#8b0000" :weight bold :underline t))))
 '(flymake-warning ((((class color) (min-colors 89)) (:foreground "#FBDE2D" :weight bold :underline t))))
 '(flyspell-duplicate ((((class color) (min-colors 89)) (:foreground "#FBDE2D" :weight bold :underline t))))
 '(flyspell-incorrect ((((class color) (min-colors 89)) (:foreground "#FF6400" :weight bold :underline t))))
 '(message-cited-text ((((class color) (min-colors 89)) (:inherit font-lock-comment))))
 '(message-header-name ((((class color) (min-colors 89)) (:foreground "#4c83ff"))))
 '(message-header-other ((((class color) (min-colors 89)) (:foreground "#00ff00"))))
 '(message-header-to ((((class color) (min-colors 89)) (:foreground "#ff1493" :weight bold))))
 '(message-header-cc ((((class color) (min-colors 89)) (:foreground "#ffff00" :weight bold))))
 '(message-header-newsgroups ((((class color) (min-colors 89)) (:foreground "#ffff00" :weight bold))))
 '(message-header-subject ((((class color) (min-colors 89)) (:foreground "#ffa500" :weight bold))))
 '(message-header-xheader ((((class color) (min-colors 89)) (:foreground "#00ff00"))))
 '(message-mml ((((class color) (min-colors 89)) (:foreground "#ffff00" :weight bold))))
 '(message-separator ((((class color) (min-colors 89)) (:inherit font-lock-comment))))
 '(rainbow-delimiters-depth-1-face ((((class color) (min-colors 89)) (:foreground "#8b0000"))))
 '(rainbow-delimiters-depth-2-face ((((class color) (min-colors 89)) (:foreground "#006400"))))
 '(rainbow-delimiters-depth-3-face ((((class color) (min-colors 89)) (:foreground "#ff1493"))))
 '(rainbow-delimiters-depth-4-face ((((class color) (min-colors 89)) (:foreground "#ffff00"))))
 '(rainbow-delimiters-depth-5-face ((((class color) (min-colors 89)) (:foreground "#00ff00"))))
 '(rainbow-delimiters-depth-6-face ((((class color) (min-colors 89)) (:foreground "#add8e6"))))
 '(rainbow-delimiters-depth-7-face ((((class color) (min-colors 89)) (:foreground "#ffa500"))))
 '(rainbow-delimiters-depth-8-face ((((class color) (min-colors 89)) (:foreground "#6a5acd"))))
 '(rainbow-delimiters-depth-9-face ((((class color) (min-colors 89)) (:foreground "#d3d3d3"))))
 '(show-paren-mismatch ((((class color) (min-colors 89)) (:foreground "#9c6363" :background "#000000"))))
 '(show-paren-match ((((class color) (min-colors 89)) (:foreground "#000000" :background "#ff1493"))))
 '(undo-tree-visualizer-active-branch-face ((((class color) (min-colors 89)) (:foreground "#ff1493" :background "#000000"))))
 '(custom-button ((((class color) (min-colors 89)) (:box (:line-width 2 :style released-button) :background "#383838" :foreground "#dcdccc"))))
 '(custom-button-unraised ((((class color) (min-colors 89)) (:background "#383838" :foreground "#dcdccc"))))
 '(default ((((class color) (min-colors 89)) (:foreground "#d3d3d3" :background "#000000")))))

(provide-theme 'cyberpunk)
